export const RUN_THE_APP = 'RUN_THE_APP';

export const GET_ALL_GROUPS_PENDING = 'GET_ALL_GROUPS_PENDING';
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
export const GET_ALL_GROUPS_REJECTED = 'GET_ALL_GROUPS_REJECTED';
export const SAVE_POST = 'SAVE_POST';
export const FETCH_POSTS = 'FETCH_POSTS';

export const CREATE_ACCOUNT_PENDING = 'CREATE_ACCOUNT_PENDING';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_REJECTED = 'CREATE_ACCOUNT_REJECTED';
export const CREATE_ACCOUNT_TO_INITIAL = 'CREATE_ACCOUNT_TO_INITIAL';

export const LOGIN_ACCOUNT_PENDING = 'LOGIN_ACCOUNT_PENDING';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_REJECTED = 'LOGIN_ACCOUNT_REJECTED';

export const EMAIL_VERIFIED_SENDED = 'EMAIL_VERIFIED_SENDED';
export const EMAIL_VERIFIED_ERROR = 'EMAIL_VERIFIED_ERROR';
export const CREATE_ACCOUNT_TO_INITIAL_ERROR = 'CREATE_ACCOUNT_TO_INITIAL_ERROR'

export const EMAIL_VERIFIED_SUCCESS = 'EMAIL_VERIFIED_SUCCESS';
export const EMAIL_VERIFIED_FAIL = 'EMAIL_VERIFIED_FAIL';
