export const RUN_THE_APP = 'RUN_THE_APP';

export const GET_ALL_GROUPS_PENDING = 'GET_ALL_GROUPS_PENDING';
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
export const GET_ALL_GROUPS_REJECTED = 'GET_ALL_GROUPS_REJECTED';
